version: '3.7'
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    command: sh -c "python app.py"
    env_file:
      - ./.env
    restart: always
    depends_on:
        - db
volumes:
  pgdata: